### PR TITLE
success backend added

### PR DESCRIPTION
**Pull request by harshalhonde21**
Added robust backend for user auth using JWT and success strong backend

### CODE REVIEW

**Comment by harshalhonde21** [comment]
Added the backend now u can merge it after reviewing i created server folder in root of the folder U can start the server by using two commands

npm install

npm start

**Comment by harshalhonde21** [comment]
added success frontend fetch api with axios and built good running application

**Review by sanjeevpurigoswami — CHANGES_REQUESTED** [review]
Still have error

image

**Comment by harshalhonde21** [comment]
@sanjeevpurigoswami  now check is it working proper

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
still have error
Screenshot 2023-10-11 at 5 40 25 PM

**Comment by harshalhonde21** [comment]
@ajaynegi45  actually this issue is troubling because it is not come in my local machine can you give another idea to do this trouble right

**Pull request closed without merging**
