### PR TITLE
improved UI of navbar

### LINKED ISSUE #6: improve navbar
The menus in the navbar section are disappearing when the size of the screen is reduced.
I can fix this issue by include a toggle menu when the size of the screen is reduced in tablet-view or mobile-view
the toggle menu will toggle when pressed and will contain all the menus of the navbar.
Assign me this task

### PR DESCRIPTION
**Pull request by SumitMangrati**
resolves #6 
this PR improves the UI design of the Navbar.
I have made the Navbar responsive by making a menu icon that toggles only while in screen lesser than 960px 
Changed the font of LOGO to a more elegant font and changed the color of the navbar from existing black to a newer glassmorphism.

### CODE REVIEW

**Comment by ajaynegi45** [comment]
> resolves #6 this PR improves the UI design of the Navbar. I have made the Navbar responsive by making a menu icon that toggles only while in screen lesser than 960px Changed the font of LOGO to a more elegant font and changed the color of the navbar from existing black to a newer glassmorphism.

**Assignee:** @SumitMangrati

Hi Sumit,

Thank you for your efforts in improving the UI design of the Navbar. I appreciate your work on making the Navbar responsive and incorporating the Glassmorphism effect.

However, I noticed a couple of issues in the code you submitted:

1. **Classname Issue:** In the code snippet you provided:

   ```jsx
   <div class={click ? "menu-links active" : "menu-links"}>
      <Navlink/>
    </div>

Please replace class with className to correctly set the class name.

2. **Navbar Size on Tablet and Phone**: It appears that the Navbar for tablet and phone sizes is smaller than expected. To ensure a better user experience, let's make it full-screen on these devices.
          <img width="172" alt="Screenshot 2023-10-05 at 11 25 51 AM" src="https://github.com/ajaynegi45/Library/assets/97536703/fc7a66cb-4da7-4564-b0a1-e775f2c878f7">


4. **Maximum Navbar Width**: We also need to set a maximum width for the Navbar to maintain a consistent layout on larger screens. Please ensure the Navbar doesn't expand beyond a certain width.
5. **Bug**: Scrolling down in safari browser, hide the navbar

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
> resolves #6 this PR improves the UI design of the Navbar. I have made the Navbar responsive by making a menu icon that toggles only while in screen lesser than 960px Changed the font of LOGO to a more elegant font and changed the color of the navbar from existing black to a newer glassmorphism.

**Assignee:** @SumitMangrati

Hi Sumit,

Thank you for your efforts in improving the UI design of the Navbar. I appreciate your work on making the Navbar responsive and incorporating the Glassmorphism effect.

However, I noticed a couple of issues in the code you submitted:

1. **Classname Issue:** In the code snippet you provided:
Please replace class with className to correctly set the class name.

   ```jsx
   <div class={click ? "menu-links active" : "menu-links"}>
      <Navlink/>
    </div>



2. **Navbar Size on Tablet and Phone**: It appears that the Navbar for tablet and phone sizes is smaller than expected. To ensure a better user experience, let's make it full-screen on these devices.
          <img width="172" alt="Screenshot 2023-10-05 at 11 25 51 AM" src="https://github.com/ajaynegi45/Library/assets/97536703/fc7a66cb-4da7-4564-b0a1-e775f2c878f7">


4. **Maximum Navbar Width**: We also need to set a maximum width for the Navbar to maintain a consistent layout on larger screens. Please ensure the Navbar doesn't expand beyond a certain width.
5. **Bug**: Scrolling down in safari browser, hide the navbar

**Comment by SumitMangrati** [comment]
shall i make the navbar for all sizes by removing the "disappearing navbar while scrolling" feature. Because i think so a static Navbar would be more good than a dynamic one and it would also remove the bug in smaller sizes where the menu bar keeps toggling on but the navbar disappears while scrolling

**Comment by ajaynegi45** [comment]
> shall i make the navbar static for all sizes by removing the "disappearing navbar while scrolling" feature. Because i think so a static Navbar would be more good than a dynamic one and it would also remove the bug in smaller sizes where the menu bar keeps toggling on but the navbar disappears while scrolling

Ok, Make static

**Pull request closed without merging**
